from abc import ABC, abstractmethod
from ..perception.slam_data import SLAMData
from ..path_planning.planner_data import PlannerData
from .actuation_data import ActuationData


class PathTrackingInterface(ABC):
    @abstractmethod
    def control(self, slam_data, planner_data):
        """
        Generate actuation commands to track the planned optimal path

        Args:
            slam_data (SLAMData): output from the Perception team via SLAM
            planner_data (PlannerData): optimal path containing way-points, generated by Path Planner

        Returns:
            ActuationData
        """
        pass
