class OptimalPath:
    """
    Container class to store the way-points generated by Path Planner

    Attributes:
        points (list of (x, y)): way-points of optimal path, its number depends on the resolution of the Path Planner
    """
    def __init__(self, points):
        self.points = points
