class PlannerData:
    """
    Container class to store the way-points generated by Path Planner

    Attributes:
        points (list of (x, y)): way-points of optimal path
    """
    def __init__(self, points):
        self.points = points

    def get_xs(self):
        return [point[0] for point in self.points]

    def get_ys(self):
        return [point[1] for point in self.points]
